name: Continuous Integration
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - feature/*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
# If multiple pushes happen quickly in succession, cancel the running build and
# start a new one.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    uses: ./.github/workflows/publish.yml
    needs:
      - build
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
